<?php
// codestat项目
//
// codestat项目
// @Description: 
// @Version: V1.0.1
// @Author: simonsun
// @Mail: 4664919@qq.com
// @Last Modified: 2017-12-27 19:38
// @Filename: index.phtml
//
//
// 

?>

<section class="content-header">
<h1> 概览 <small> 汇总数据</small>
</h1>
<ol class="breadcrumb">
<li><a href="/"><i class="fa fa-dashboard"></i> 首页</a></li>
<li class="active">版本号表[revision]</li>
</ol>
</section>
<section class="content">
<?php /*
------------------------- 内容 start--------------------------
 */?>
<div class = "box">
<div class="box box-primary">
<div class="box-header with-border">
     <h3 class="box-title">筛选</h3>
</div>
<?php /*
------------------------- 搜索开始 --------------------------
 */?>
<link rel="stylesheet" href="/static/plugins/daterangepicker/daterangepicker-bs3.css">
<div class = "row ">
<div class="col-xs-12">
    <form role="form" action="" method="get">

    <div class="col-xs-3">
        <div class="box-body">
        <div class="input-group">
        <div class="input-group-btn">

        <button class="btn btn-info" type="button"><i class="fa fa-calendar"></i> 起始时间</button>
        </div>
        <input type="text" class="form-control pull-right" name="begin_date" id="begin_date" value="<?php 
 if (is_object($time)){
     echo $time->begin_date;
 }
?>">
        </div>
        </div>
    </div>
    <div class="col-xs-3">
        <div class="box-body">
        <div class="input-group">
        <div class="input-group-btn">

        <button class="btn btn-info" type="button"><i class="fa fa-calendar"></i> 结束时间</button>
        </div>
        <input type="text" class="form-control pull-right" name="end_date" id="end_date" value="<?php 
if (is_object($time)){
    echo $time->end_date;
}
?>">
        </div>
        </div>
    </div>


    <?php /*----- 搜索截止 -------*/?>
    <div class="clearfix"></div>
    <div class="box-footer">
    <div class="col-xs-12">
    <button class="btn btn-primary" type="submit" id="sub">搜索</button>

    </div>
    </div>
    </form>

</div>
</div>
<?php /*
------------------------- 搜索结束 --------------------------
 */?>




<div class="row">

    <div class="col-md-6">
      <div class="info-box bg-green">
        <span class="info-box-icon"><i class="fa fa-heart-o"></i></span>
        <div class="info-box-content">
          <span class="info-box-text">总提交次数</span>
          <span class="info-box-number"><?php echo $r_total_count?>次</span>
          <div class="progress">
          <div style="width: <?php echo number_format($rp_count['a_line']/$r_total_count,3) ?>%" class="progress-bar"></div>
          </div>
          <span class="progress-description">
        <i class="fa fa-plus-square-o"></i>
        <m title="新增行数"><?php echo $rp_count['a_line']?></m>  
&nbsp;&nbsp;| &nbsp;&nbsp;
        <i class="fa fa-minus-square-o"></i>
        <?php echo $rp_count['d_line']?>


          </span>
        </div><!-- /.info-box-content -->
      </div><!-- /.info-box -->
    </div>

    <div class="col-md-6">
      <div class="info-box bg-aqua">
        <span class="info-box-icon"><i class="fa fa-bookmark-o"></i></span>
        <div class="info-box-content">
          <span class="info-box-text">总项目数</span>
          <span class="info-box-number">
        <i class="fa fa-adn"></i>
<?php echo count($apps)?>个项目</span>
          <div class="progress">
          <div style="width: <?php echo number_format($rp_count['a_line']/$r_total_count,3) ?>%" class="progress-bar"></div>
          </div>
          <span class="progress-description">
        <i class="fa fa-user"></i>
            共 <?php echo count($authors)?> 个用户
          </span>
        </div>
      </div>
    </div>

</div>

<div class="row">
<div class="col-md-12">
    <div id="chart_pie_ci_count" style=";height:750px;"></div>
    <hr />
</div>
<div class="col-md-12">
    <div id="chart_pie_line_count" style=";height:750px;"></div>
    <hr />
</div>
</div>


<div class="row">
<div class="col-md-12">
<div class="box">
        <div class="box-header with-border">
              <h3 class="box-title"></h3>
        </div>
            <!-- /.box-header -->
        <div class="box-body">
          <table class="table table-bordered">
                <tbody><tr>
                  <th style="">序号</th>
                  <th>项目名称</th>
                  <th>提交次数</th>
                  <th>新增行数</th>
                  <th>删除行数</th>
        </tr>
<?php $key=0;foreach ($apps as $app){$key ++;?>
        <tr>
                <td><?php echo $key?>.</td>
                  <td><a href="/project/index?project=<?php echo $app['en_name']?>"><?php echo $app['name']?>[<?php echo $app['en_name']?>]</a></td>
                  <td><?php echo $app['r_count']?></td>
                  <td><?php echo $app['a_line']?></td>
                  <td><?php echo $app['d_line']?></td>
                </tr>
<?php }?>
              </tbody></table>
            </div>
          </div>
</div>
</div>


<div class="row">
<div class="col-md-12">
<div class="box-header">
<h3 class="box-title" >项目列表</h3>
</div>
    <?php foreach ($apps as $app){?>
<a href="/project/index?project=<?php echo $app['en_name']?>" class="btn btn-app" style="height:auto">
<i class="fa fa-inbox"></i> 
<?php echo $app['name']?><br>
<?php echo $app['en_name']?>
</a>
    <?php }?>
</div>
</div>


<div class="row">
<div class="col-md-12">
<div class="box-header">
<h3 class="box-title" >用户列表</h3>
</div>
    <?php foreach ($authors as $author){?>
<a href="/author/index?author=<?php echo $author?>" class="btn btn-app" style="height:auto">
<i class="fa fa-inbox"></i> 
<?php echo $author?><br>
</a>
    <?php }?>
</div>
</div>

<?php /*
------------------------- 内容 end --------------------------
 */?>
</div>
</div>
</section>
 <script>
 $(function () {

     $('#begin_date').daterangepicker({
     singleDatePicker: true,
         format: 'YYYY-MM-DD',
         startDate: moment()
 });
     $('#end_date').daterangepicker({
     singleDatePicker: true,
         format: 'YYYY-MM-DD',
         startDate: moment()
 });
 });

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
<script src="/static/plugins/daterangepicker/daterangepicker.js"></script>





<script src="/static/js/echarts.all.js"></script>
 <script type="text/javascript">
 // 基于准备好的dom，初始化echarts实例
 var myChart = echarts.init(document.getElementById('chart_pie_ci_count'),'macarons');
option = {
title : {text: '项目提交次数概览',x:'center'},
    tooltip : {trigger: 'item',formatter: "{a} {b},提交次数{c}, 占比: {d}%"},
    series : [
 {
     name: '',
         type: 'pie',
         radius : '40%',
         center: ['50%', '60%'],
         data:
<?php 
?>
<?php $_tmp=array();foreach ($apps as $app){
$_tmp[] =  array(
    "value" => $app['r_count'],
    "name" => "{$app['name']}[{$app['en_name']}]",
);
};echo json_encode($_tmp);?>
,
    itemStyle: {emphasis: {
    shadowBlur: 10,
        shadowOffsetX: 0
}}
 }
]
 };

myChart.setOption(option);

// 基于准备好的dom，初始化echarts实例
var myChart = echarts.init(document.getElementById('chart_pie_line_count'),'macarons');
option = {
title : {text: '代码新增行数概览',x:'center'},
    tooltip : {trigger: 'item',formatter: "{a} {b},提交行数{c}, 占比: {d}%"},
    series : [
{
    name: '',
        type: 'pie',
        radius : '40%',
        center: ['50%', '60%'],
        data:
<?php 
?>
<?php $_tmp=array();foreach ($apps as $app){
$_tmp[] =  array(
    "value" => $app['a_line'],
    "name" => "{$app['name']}[{$app['en_name']}]",
);
};echo json_encode($_tmp);?>
,
    itemStyle: {emphasis: {
    shadowBlur: 10,
        shadowOffsetX: 0
}}
}
]
};

myChart.setOption(option);
</script>

