<?php
// codestat项目
//
// codestat项目
// @Description: 
// @Version: V1.0.1
// @Author: simonsun
// @Mail: 4664919@qq.com
// @Last Modified: 2017-12-27 19:38
// @Filename: index.phtml
//
//
// 

?>

<section class="content-header">
<h1> 分析 <small> 汇总数据</small>
</h1>
<ol class="breadcrumb">
<li><a href="/"><i class="fa fa-dashboard"></i> 首页</a></li>
<li><a href="/index/"><i class="fa fa-dashboard"></i> 汇总 </a></li>
<li class="active">分析</li>
</ol>
</section>
<section class="content">
<?php /*
------------------------- 内容 start--------------------------
*/?>
<div class = "box">
<div class="box box-primary">
<div class="box-header with-border">
     <h3 class="box-title">筛选</h3>
</div>
<?php /*
------------------------- 搜索开始 --------------------------
*/?>
<link rel="stylesheet" href="/static/plugins/daterangepicker/daterangepicker-bs3.css">
<div class = "row ">
<div class="col-xs-12">
<form role="form" action="" method="get">


<?php /*   显示统计纬度 － 年月日周 */?>
<div class="col-xs-12"><div class="box-body">

    <div class="btn-group" data-toggle="buttons">
      <span type="button" class="btn btn-default _parse_input_select_text" >纬度:</span>
        <?php echo \HtmlService::GenRadio($data_dimension_list,$data_dimension,"data_dimension")?>
    </div>

</div></div>


<?php /*   项目   */?>
<div class="col-xs-12"><div class="box-body _parse_input_select_app_box">

    <div class="btn-group" data-toggle="buttons">
      <span type="button" class="btn btn-default _parse_input_select_app_text" >项目:</span>
      <?php echo \HtmlService::GenCheckboxSytleApp($app_list,$app_name,"app_name[]")?>
    </div>

</div></div>


<?php /*   用户   */?>
<div class="col-xs-12"><div class="box-body">

    <div class="btn-group" data-toggle="buttons">

      <span type="button" class="btn btn-default _parse_input_select_text" >作者:</span>
      <?php echo \HtmlService::GenCheckbox($author_list,$author_name,"author_name[]")?>
    </div>

</div></div>


<?php /*   是否开启过滤  */?>
<div class="col-xs-12"><div class="box-body">

    <div class="btn-group" data-toggle="buttons">
      <span type="button" class="btn btn-default _parse_input_select_text" >过滤:</span>
        <?php echo \HtmlService::GenRadio($filter_list,$filter_name,"filter_name")?>
    </div>

</div></div>

<?php /*   动作类别  */?>
<div class="col-xs-12"><div class="box-body">

    <div class="btn-group" data-toggle="buttons">

      <span type="button" class="btn btn-default _parse_input_select_text" >类别:</span>
      <?php echo \HtmlService::GenCheckbox($action_list,$action_name,"action_name[]")?>
    </div>

</div></div>












    <div class="col-xs-3">
        <div class="box-body">
        <div class="input-group">
        <div class="input-group-btn">
    
        <button class="btn btn-info" type="button"><i class="fa fa-calendar"></i> 起始时间</button>
        </div>
        <input type="text" class="form-control pull-right" name="begin_date" id="begin_date" value="<?php 
if (is_object($time)){
    echo $time->begin_date;
}
?>">
        </div>
        </div>
    </div>
    <div class="col-xs-3">
        <div class="box-body">
        <div class="input-group">
        <div class="input-group-btn">
    
        <button class="btn btn-info" type="button"><i class="fa fa-calendar"></i> 结束时间</button>
        </div>
        <input type="text" class="form-control pull-right" name="end_date" id="end_date" value="<?php 
if (is_object($time)){
    echo $time->end_date;
}
?>">
        </div>
        </div>
    </div>


    <?php /*----- 搜索截止 -------*/?>
    <div class="clearfix"></div>
    <div class="box-footer">
    <div class="col-xs-12">
    <button class="btn btn-primary" type="submit" id="sub">搜索</button>

    </div>
    </div>
    </form>

</div>
</div>
<?php /*
------------------------- 搜索结束 --------------------------
*/?>

<div class="row">

<?php /*------------------------- 作者统计--------------------------*/?>
<div class="col-md-6">
<div class="box">
        <div class="box-header with-border">
              <h3 class="box-title">作者</h3><small> 每个人所有的代码修改数</small>
        </div>
            <!-- /.box-header -->
        <div class="box-body">
          <table class="table table-bordered">
                <tbody><tr>
                  <th style="">序号</th>
                  <th>作者</th>
                  <th>提交次数</th>
                  <th>新增行数</th>
                  <th>删除行数</th>
                  <th>操作行数</th>
        </tr>
<?php foreach ($total['author_list'] as  $key => $data){?>
        <tr>
                <td><?php echo $key?>.</td>
                  <td><?php echo $data['author']?></td>
                  <td><?php echo $data['r_id']?></td>
                  <td><?php echo $data['a_line']?></td>
                  <td><?php echo $data['d_line']?></td>
                  <td><?php echo $data['line']?></td>
                </tr>
<?php }?>
              </tbody></table>
            </div>
          </div>
</div>

<?php /*------------------------- 项目统计--------------------------*/?>
<div class="col-md-6">
<div class="box">
        <div class="box-header with-border">
              <h3 class="box-title">项目</h3><small> 每个项目的代码修改数</small>
        </div>
            <!-- /.box-header -->
        <div class="box-body">
          <table class="table table-bordered">
                <tbody><tr>
                  <th style="">序号</th>
                  <th>项目</th>
                  <th>提交次数</th>
                  <th>新增行数</th>
                  <th>删除行数</th>
                  <th>操作行数</th>
        </tr>
<?php foreach ($total['project_list'] as  $key => $data){?>
        <tr>
                <td><?php echo $key?>.</td>
                  <td><?php echo $data['project_name']?></td>
                  <td><?php echo $data['r_id']?></td>
                  <td><?php echo $data['a_line']?></td>
                  <td><?php echo $data['d_line']?></td>
                  <td><?php echo $data['line']?></td>
                </tr>
<?php }?>
              </tbody></table>
            </div>
          </div>
</div>



</div>


<?php /*------------------------- 项目统计--------------------------*/?>
<div class="row">
<div class="col-md-12">
<div class="box">
        <div class="box-header with-border">
              <h3 class="box-title">项目、作者</h3><small> 每个项目中每个人的代码修改数</small>
        </div>
            <!-- /.box-header -->
        <div class="box-body">
          <table class="table table-bordered">
                <tbody><tr>
                  <th style="">序号</th>
                  <th>项目</th>
                  <th>作者</th>
                  <th>提交次数</th>
                  <th>新增行数</th>
                  <th>删除行数</th>
                  <th>操作行数</th>
        </tr>
<?php foreach ($total['project_author_list'] as  $key => $data){?>
        <tr>
                <td><?php echo $key?>.</td>
                  <td><?php echo $data['project_name']?></td>
                  <td><?php echo $data['author']?></td>
                  <td><?php echo $data['r_id']?></td>
                  <td><?php echo $data['a_line']?></td>
                  <td><?php echo $data['d_line']?></td>
                  <td><?php echo $data['line']?></td>
                </tr>
<?php }?>
              </tbody></table>
            </div>
          </div>
</div>
</div>











<div class="row">
<div class="col-md-12">
    <div id="chart_pie_line_count" style=";height:350px;"></div>
    <hr />
</div>
</div>

<script src="/static/js/echarts.all.js"></script>
<script type="text/javascript">
        var myChart = echarts.init(document.getElementById('chart_pie_line_count'),'macarons');
option = {
    tooltip : {
        trigger: 'axis'
    },
    legend: {
        data:['用户a','联盟广告','视频广告','直接访问','搜索引擎']
    },
    toolbox: {
        show : true,
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            magicType : {show: true, type: ['line', 'bar', 'stack', 'tiled']},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    calculable : true,
    xAxis : [
        {
            type : 'category',
            boundaryGap : false,
            data : ['时间','周二','周三','周四','周五','周六','周日']
        }
    ],
    yAxis : [
        {
            type : 'value'
        }
    ],
    series : [
        {
            name:'用户a',
            type:'line',
            stack: '总量',
            itemStyle: {normal: {areaStyle: {type: 'default'}}},
            data:[120, 132, 101, 134, 90, 230, 210]
        },
        {
            name:'联盟广告',
            type:'line',
            stack: '总量',
            itemStyle: {normal: {areaStyle: {type: 'default'}}},
            data:[220, 182, 191, 234, 290, 330, 310]
        },
        {
            name:'视频广告',
            type:'line',
            stack: '总量',
            itemStyle: {normal: {areaStyle: {type: 'default'}}},
            data:[150, 232, 201, 154, 190, 330, 410]
        },
        {
            name:'直接访问',
            type:'line',
            stack: '总量',
            itemStyle: {normal: {areaStyle: {type: 'default'}}},
            data:[320, 332, 301, 334, 390, 330, 320]
        },
        {
            name:'搜索引擎',
            type:'line',
            stack: '总量',
            itemStyle: {normal: {areaStyle: {type: 'default'}}},
            data:[820, 932, 901, 934, 1290, 1330, 1320]
        }
    ]
};
myChart.setOption(option);
</script>
                    



<pre>
<?php print_r($data)?>
</pre>


<?php /*
------------------------- 内容 end --------------------------
*/?>
</div>
</div>
</section>
<script>
$(function () {

    $('#begin_date').daterangepicker({
        singleDatePicker: true,
            format: 'YYYY-MM-DD',
            startDate: moment()
    });
    $('#end_date').daterangepicker({
        singleDatePicker: true,
            format: 'YYYY-MM-DD',
            startDate: moment()
    });
});

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
<script src="/static/plugins/daterangepicker/daterangepicker.js"></script>
