<?php
// codestat项目
//
// codestat项目
// @Description: 
// @Version: V1.0.1
// @Author: simonsun
// @Mail: 4664919@qq.com
// @Last Modified: 2017-12-27 19:38
// @Filename: index.phtml
//
//

?>

<section class="content-header">
<h1> 分析 <small> 汇总数据</small>
</h1>
<ol class="breadcrumb">
<li><a href="/"><i class="fa fa-dashboard"></i> 首页</a></li>
<li><a href="/index/"><i class="fa fa-dashboard"></i> 汇总 </a></li>
<li class="active">分析</li>
</ol>
</section>
<section class="content">
<?php /*
------------------------- 内容 start--------------------------
*/?>
<div class = "box">
<div class="box box-primary">
<div class="box-header with-border">
     <h3 class="box-title">筛选</h3>
</div>
<?php /*
------------------------- 搜索开始 --------------------------
*/?>
<link rel="stylesheet" href="/static/plugins/daterangepicker/daterangepicker-bs3.css">
<div class = "row ">
<div class="col-xs-12">
<form role="form" action="" method="get">



<?php /*   是否开启过滤  */?>
<div class="col-xs-4"><div class="box-body">

    <div class="btn-group" data-toggle="buttons">
      <span type="button" class="btn btn-default _parse_input_select_text" >过滤:</span>
        <?php echo \HtmlService::GenRadio($filter_list,$filter_name,"filter_name")?>
    </div>

</div></div>



<?php /*   后缀  */?>
<div class="col-xs-6"><div class="box-body">

    <div class="btn-group" data-toggle="buttons">
      <span type="button" class="btn btn-default _parse_input_select_text" >后缀:</span>
        <?php echo \HtmlService::GenCheckbox($suffix_list,$suffix_name,"suffix")?>
    </div>

</div></div>
<?php /*   自定义后缀  */?>


<div class="clearfix"></div>
    <div class="">
    <div class="col-xs-4">
        <div class="box-body">
        <div class="input-group">
        <div class="input-group-btn">
      <span type="button" class="btn btn-default _parse_input_select_text" >自定义后缀:</span>
    
        </div>

      <input type="text" class="form-control pull-right" name="custom_suffix"  value="<?php echo $custom_suffix?>"/>


        </div>
        </div>
    </div>

    </div>
<div class="clearfix"></div>







    <div class="col-xs-3">
        <div class="box-body">
        <div class="input-group">
        <div class="input-group-btn">
    
        <button class="btn btn-info" type="button"><i class="fa fa-calendar"></i> 起始时间</button>
        </div>
        <input type="text" class="form-control pull-right" name="begin_date" id="begin_date" value="<?php 
if (is_object($time)){
    echo $time->begin_date;
}
?>">
        </div>
        </div>
    </div>
    <div class="col-xs-3">
        <div class="box-body">
        <div class="input-group">
        <div class="input-group-btn">
    
        <button class="btn btn-info" type="button"><i class="fa fa-calendar"></i> 结束时间</button>
        </div>
        <input type="text" class="form-control pull-right" name="end_date" id="end_date" value="<?php 
if (is_object($time)){
    echo $time->end_date;
}
?>">
        </div>
        </div>
    </div>


    <?php /*----- 搜索截止 -------*/?>
    <div class="clearfix"></div>
    <div class="box-footer">
    <div class="col-xs-12">
    <button class="btn btn-primary" type="submit" id="sub">搜索</button>

    </div>
    </div>
    </form>

</div>
</div>
<?php /*
------------------------- 搜索结束 --------------------------
*/?>

<div class="row">

<?php /*------------------------- 作者统计--------------------------*/?>
<div class="col-md-6">
<div class="box">
        <div class="box-header with-border">
              <h3 class="box-title">作者</h3>
                <small> 每个人所有的代码修改数</small>
                <a class="pull-right" href="/index/total_excel_author?<?php echo $exce_url?>"> 导出到excel </a>
        </div>
            <!-- /.box-header -->
        <div class="box-body">
          <table class="table table-bordered">
                <tbody><tr>
                  <th style="">序号</th>
                  <th>作者</th>
                  <th>提交文件数</th>
                  <th>新增行数</th>
                  <th>删除行数</th>
                  <th>操作行数</th>
                  <th></th>
        </tr>
<?php foreach ($total['author_list'] as  $key => $data){?>
        <tr>
                <td><?php echo $key+1?>.</td>
                  <td><a href="/author/index?author=<?php echo $data['author']?>"><?php echo $data['author']?></a></td>
                  <td><?php echo $data['r_id']?></td>
                  <td><?php echo $data['a_line']?></td>
                  <td><?php echo $data['d_line']?></td>
                  <td><?php echo $data['line']?></td>
                  <td><a href="/revision_path/index?search_author=<?php echo $data['author']?>&search_status%5B%5D=1&begin_date=<?php echo $time->begin_date?>&end_date=<?php echo $time->end_date?>&sort=desc">详情</a></td>
                </tr>
<?php }?>
              </tbody></table>
            </div>
          </div>
</div>

<?php /*------------------------- 项目统计--------------------------*/?>
<div class="col-md-6">
<div class="box">
        <div class="box-header with-border">
              <h3 class="box-title">项目</h3><small> 每个项目的代码修改数</small>
                <a class="pull-right" href="/index/total_excel_project?<?php echo $exce_url?>"> 导出到excel </a>
        </div>
            <!-- /.box-header -->
        <div class="box-body">
          <table class="table table-bordered">
                <tbody><tr>
                  <th style="">序号</th>
                  <th>项目</th>
                  <th>提交文件数</th>
                  <th>新增行数</th>
                  <th>删除行数</th>
                  <th>操作行数</th>
        </tr>
<?php foreach ($total['project_list'] as  $key => $data){?>
        <tr>
                <td><?php echo $key+1?>.</td>
                  <td><a href="/project/index?project=<?php echo $data['project_name'] ?>"><?php echo \StatService::GetProjectByName($data['project_name'])['name']?>[<?php echo $data['project_name']?>]</a></td>
                  <td><?php echo $data['r_id']?></td>
                  <td><?php echo $data['a_line']?></td>
                  <td><?php echo $data['d_line']?></td>
                  <td><?php echo $data['line']?></td>
                </tr>
<?php }?>
              </tbody></table>
            </div>
          </div>
</div>



</div>


<?php /*------------------------- 项目统计--------------------------*/?>
<div class="row">
<div class="col-md-12">
<div class="box">
        <div class="box-header with-border">
              <h3 class="box-title">项目、作者</h3><small> 每个项目中每个人的代码修改数</small>
                <a class="pull-right" href="/index/total_excel_author_project?<?php echo $exce_url?>"> 导出到excel </a>
        </div>
            <!-- /.box-header -->
        <div class="box-body">
          <table class="table table-bordered">
                <tbody><tr>
                  <th style="">序号</th>
                  <th>项目</th>
                  <th>
                    <table class="table"><tbody>
                                    <tr>
                                      <th style="width:20%">作者</th>
                                      <th style="width:20%">提交文件数</th>
                                      <th style="width:20%">新增行数</th>
                                      <th style="width:20%">删除行数</th>
                                      <th style="width:20%">操作行数</th>
                                    </tr>
                    </tbody></table>

                    </th>
        </tr>
<?php $key=0;foreach ($total['project_author_list'] as  $project_name => $p_data){$key++;?>
        <tr>
                <td><?php echo $key?>.</td>
                <td><a href="/project/index?project=<?php echo $project_name ?>"><?php echo \StatService::GetProjectByName($project_name)['name']?>[<?php echo $project_name?>]</a></td>
                    
<td>
<table class="table"><tbody>
<?php foreach ($p_data as $data){?>
                
        <tr>
                  <td style="width:20%"><a href="/author/index?author=<?php echo $data['author']?>"><?php echo $data['author']?></a></td>
                  <td style="width:20%"><?php echo $data['r_id']?></td>
                  <td style="width:20%"><?php echo $data['a_line']?></td>
                  <td style="width:20%"><?php echo $data['d_line']?></td>
                  <td style="width:20%"><?php echo $data['line']?></td>
        </tr>
<?php }?>
</tbody></table>
</td>
                </tr>
<?php }?>
              </tbody></table>
            </div>
          </div>
</div>
</div>












<?php /*
------------------------- 内容 end --------------------------
*/?>
</div>
</div>
</section>
<script>
$(function () {

    $('#begin_date').daterangepicker({
        singleDatePicker: true,
            format: 'YYYY-MM-DD',
            startDate: moment()
    });
    $('#end_date').daterangepicker({
        singleDatePicker: true,
            format: 'YYYY-MM-DD',
            startDate: moment()
    });
});

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
<script src="/static/plugins/daterangepicker/daterangepicker.js"></script>
