<?php
/**
 *
 * codestat项目 
 * @date2015-10-19 07:40:35
 * @author simonsun
 * @email 4664919@qq.com
 */
    function showMenuActive($url){
        if(isset($_GET['_url']) && $_GET['_url'] == $url){
            return "active";
        }
        return "";
    }

?>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">


      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <!-- Optionally, you can add icons to the links -->
        <li class="<?php echo showMenuActive("/")?>"><a href="/"><i class="fa fa-link"></i> <span>首页</span></a></li>
        <li class="<?php echo showMenuActive("/index/overview")?>"><a href="/index/overview"><i class="fa fa-link"></i> <span>概览</span></a></li>
        <li class="<?php echo showMenuActive("/index/total")?>"><a href="/index/total"><i class="fa fa-link"></i> <span>统计</span></a></li>
        <li class="<?php echo showMenuActive("/author/total")?>"><a href="/author/total"><i class="fa fa-link"></i> <span>用户</span></a></li>
        <li class="<?php echo showMenuActive("/revision/index")?>"><a href="/revision/index"><i class="fa fa-link"></i>
 <span>版本</span>
</a></li>
        <li class="<?php echo showMenuActive("/revision_path/index")?>"><a href="/revision_path/index"><i class="fa fa-link"></i>
 <span>版本详情</span>
</a></li>
        <li class="<?php echo showMenuActive("/backend/system_status")?>"><a href="/backend/system_status"><i class="fa fa-link"></i> <span>服务状态管理</span></a></li>
<!--
        <li class="<?php echo showMenuActive("/index/parse")?>"><a href="/index/parse"><i class="fa fa-link"></i> <span>分析</span></a></li>
        <li class="<?php echo showMenuActive("/index/project")?>"><a href="/index/project"><i class="fa fa-link"></i> <span>项目</span></a></li>
-->
        <?php /*
        <li class="treeview">
          <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span> <i class="fa fa-angle-left pull-right"></i></a>
          <ul class="treeview-menu">
            <li><a href="#">Link in level 2</a></li>
            <li><a href="#">Link in level 2</a></li>
          </ul>
        </li>
        */?>
      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>
