<?php
// 
// manage project
// user 用户 view view
// @date 2017-12-28
//
?>

<section class="content-header">
<h1> 查看用户[user] <small>查看</small>
</h1>
<ol class="breadcrumb">
<li><a href="/"><i class="fa fa-dashboard"></i> 首页</a></li>
<li><a href="/user"><i class=""></i>>用户[user]</a></li>
<li class="active">查看</li>
</ol>
</section>
<section class="content">
<?php /*
------------------------- 内容 start--------------------------
*/?>
    <div class="box box-default">

<div class="box-body">
    <div class="form-group">
    <label for="">主键ID : </label>
<?php echo $user->pkid?>
    </div>
    <div class="form-group">
    <label for="">唯一ID : </label>
<?php echo $user->unique_id?>
    </div>
    <div class="form-group">
    <label for="">昵称 : </label>
<?php echo $user->nick?>
    </div>
    <div class="form-group">
    <label for="">邮箱 : </label>
<?php echo $user->mail?>
    </div>
    <div class="form-group">
    <label for="">注释 : </label>
<?php echo $user->desc?>
    </div>
    <div class="form-group">
    <label for="">密码 : </label>
<?php echo $user->pwd?>
    </div>
    <div class="form-group">
    <label for="">创建时间 : </label>
<?php echo $user->ctime?>
    </div>
    <div class="form-group">
    <label for="">更新时间 : </label>
<?php echo $user->modify?>
    </div>
    <div class="form-group">
    <label for="">头像 : </label>
<?php echo $user->avatar?>
    </div>
    <div class="form-group">
    <label for="">状态 : </label>

        <?php echo \HtmlService::GenText($status_list,$user->status)?>
    </div>


    <div class="box-footer">
    <button class="btn btn-primary" id="go_back" type="submit" >返回</button>
    </div>
</div>

     <div class="clearfix"></div>

<?php /*
------------------------- 内容 end --------------------------
*/?>
</div>
</section>
