<?php
// 
// manage project
// revision_path 版本号具体的提交路径 view view
// @date 2017-12-26
//
?>

<section class="content-header">
<h1> 查看版本号具体的提交路径[revision_path] <small>查看</small>
</h1>
<ol class="breadcrumb">
<li><a href="/"><i class="fa fa-dashboard"></i> 首页</a></li>
<li><a href="/revision_path"><i class=""></i>>版本号具体的提交路径[revision_path]</a></li>
<li class="active">查看</li>
</ol>
</section>
<section class="content">
<?php /*
------------------------- 内容 start--------------------------
*/?>
    <div class="box box-default">

<div class="box-body">
    <div class="form-group">
    <label for="">主键ID : </label>
<?php echo $revision_path->pkid?>
    </div>
    <div class="form-group">
    <label for="">版本号ID : </label>
<?php echo $revision_path->r_id?>
    </div>
    <div class="form-group">
    <label for="">修改时间 : </label>
<?php echo $revision_path->modify?>
    </div>
    <div class="form-group">
    <label for="">路径的类型 : </label>

        <?php echo \HtmlService::GenText($kind_list,$revision_path->kind)?>
    </div>
    <div class="form-group">
    <label for="">提交的类型 : </label>

        <?php echo \HtmlService::GenText($action_list,$revision_path->action)?>
    </div>
    <div class="form-group">
    <label for="">路径 : </label>
<?php echo $revision_path->path?>
    </div>
    <div class="form-group">
    <label for="">提交svn的作者 : </label>
<?php echo $revision_path->author?>
    </div>
    <div class="form-group">
    <label for="">项目名称 : </label>
<?php echo $revision_path->project_name?>
    </div>
    <div class="form-group">
    <label for="">版本提交时间 : </label>
<?php echo $revision_path->r_time?>
    </div>
    <div class="form-group">
    <label for="">增加行数 : </label>
<?php echo $revision_path->a_line?>
    </div>
    <div class="form-group">
    <label for="">减少行数 : </label>
<?php echo $revision_path->d_line?>
    </div>
    <div class="form-group">
    <label for="">执行的diff命令 : </label>
<?php echo $revision_path->cmd?>
    </div>
    <div class="form-group">
    <label for="">状态 : </label>

        <?php echo \HtmlService::GenText($status_list,$revision_path->status)?>
    </div>


    <div class="box-footer">
    <button class="btn btn-primary" id="go_back" type="submit" >返回</button>
    </div>
</div>

     <div class="clearfix"></div>

<?php /*
------------------------- 内容 end --------------------------
*/?>
</div>
</section>
