<?php
// 
// manage project
// revision 版本号 view index
// @date 2017-12-26
//

?>

<section class="content-header">
<h1> 版本号[revision] <small> 列表</small>
</h1>
<ol class="breadcrumb">
<li><a href="/"><i class="fa fa-dashboard"></i> 首页</a></li>
<li class="active">版本号[revision]</li>
</ol>
</section>
<section class="content">
<?php /*
------------------------- 内容 start--------------------------
*/?>
<div class = "box">
<div class="box box-primary">
<div class="box-header with-border">
     <h3 class="box-title">筛选</h3>
</div>

<?php /*
------------------------- 搜索开始 --------------------------
*/?>
<div class = "row ">
<div class="col-xs-12">
    <form id="index_search" role="form" action="" method="get">
    <div class="col-xs-4">
        <div class="box-body">
        <div class="input-group">
                <div class="input-group-btn">
        <button class="btn btn-info" type="button">主键ID</button>
        </div>
        <?php echo \HtmlService::GenInput($search_pkid,"search_pkid")?>
        </div>
        </div>
    </div>
    <div class="col-xs-4">
        <div class="box-body">
        <div class="input-group">
                <div class="input-group-btn">
        <button class="btn btn-info" type="button">版本号ID</button>
        </div>
        <?php echo \HtmlService::GenInput($search_r_id,"search_r_id")?>
        </div>
        </div>
    </div>
    <div class="col-xs-4">
        <div class="box-body">
        <div class="input-group">
                <div class="input-group-btn">
        <button class="btn btn-info" type="button">项目名称</button>
        </div>
        <?php echo \HtmlService::GenInput($search_project_name,"search_project_name")?>
        </div>
        </div>
    </div>
    <div class="col-xs-4">
        <div class="box-body">
        <div class="input-group">
                <div class="input-group-btn">
        <button class="btn btn-info" type="button">提交svn的作者</button>
        </div>
        <?php echo \HtmlService::GenInput($search_author,"search_author")?>
        </div>
        </div>
    </div>
    <div class="col-xs-4">
        <div class="box-body">
        <div class="input-group">
                <div class="input-group-btn">
        <button class="btn btn-info" type="button">版本提交时间</button>
        </div>
        <?php echo \HtmlService::GenInput($search_r_time,"search_r_time")?>
        </div>
        </div>
    </div>
    <!-- div class="col-xs-4">
        <div class="box-body">
        <div class="input-group">
                <div class="input-group-btn">
        <button class="btn btn-info" type="button">修改时间</button>
        </div>
        <?php echo \HtmlService::GenInput($search_modify,"search_modify")?>
        </div>
        </div>
    </div -->


    <?php /*----- 搜索截止 -------*/?>
    <div class="clearfix"></div>
    <div class="box-footer">
    <div class="col-xs-12">
    <button class="btn btn-primary" type="submit" id="sub">搜索</button>
    <input id="order" type="hidden" name="order" value="<?php echo $order?>" />
    <input id="sort" type="hidden" name="sort" value="<?php echo $sort?>" />

    
    </div>
    </div>
    </form>

</div>
</div>
<?php /*
------------------------- 搜索结束 --------------------------
*/?>

<div class="box-body">
<table id="index_list_tab" class="table table-bordered table-hover">
<thead>
<tr>
	<th class='tr' id="list_id_r_id" name="r_id">版本号ID</th>
	<th class='tr' id="list_id_project_name" name="project_name">项目名称</th>
	<th class='tr' id="list_id_author" name="author">提交svn的作者</th>
	<th class='tr' id="list_id_r_time" name="r_time">版本提交时间</th>
	<!-- th class='tr' id="list_id_modify" name="modify">修改时间</th -->

<th>操作</th>
</tr>
</thead>
<tbody>
<?php 
if($content){
foreach($content as &$con){?>
<tr>
    <td><?php echo $con["r_id"]?></td>
    <td><a href='/project/index?project=<?php echo $con['project_name']?>'><?php echo $con["project_name"]?></a></td>
    <td><?php echo $con["author"]?></td>
    <td><?php echo date("Y-m-d H:i:s",$con["r_time"]);?></td>
    <!-- td><?php echo $con["modify"]?></td -->

<td>        <a href="/revision_path/index?search_r_id=<?php echo $con['r_id']?>">查看</a></td>
</tr>
<?php 
}}
?>
</tbody>
</table>
<div class="clearfix"></div>

</div>

<?php /*
------------------------- page --------------------------
*/?>
<div class="box-body">
<div class="row">
<div class="col-sm-5">
<div class="dataTables_info" id="example2_info" role="status" aria-live="polite">
共<?php echo $total?>条
,<?php echo $page_num?>页
</div></div>
<div class="col-sm-7">
<div class="dataTables_paginate paging_simple_numbers" id="pagination_box">

<ul class="pagination">
<?php echo $page_html?>
</ul>


</div>
</div>
</div>
</div>
<?php /*
------------------------- page end --------------------------
*/?>
<?php /*
------------------------- 内容 end --------------------------
*/?>
</div>
</div>
</section>
